// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CostofLiving
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("from")]
        public From From { get; set; }

        [JsonProperty("to")]
        public From To { get; set; }

        [JsonProperty("comparison")]
        public Comparison Comparison { get; set; }
    }

    public partial class Comparison
    {
        [JsonProperty("costDifference")]
        public double CostDifference { get; set; }

        [JsonProperty("direction")]
        public string Direction { get; set; }

        [JsonProperty("salaryEquivalent")]
        public SalaryEquivalent SalaryEquivalent { get; set; }
    }

    public partial class SalaryEquivalent
    {
        [JsonProperty("description")]
        public string Description { get; set; }

        [JsonProperty("fromSalary")]
        public long FromSalary { get; set; }

        [JsonProperty("equivalentSalary")]
        public long EquivalentSalary { get; set; }
    }

    public partial class From
    {
        [JsonProperty("searchedLocation")]
        public string SearchedLocation { get; set; }

        [JsonProperty("region")]
        public string Region { get; set; }

        [JsonProperty("regionName")]
        public string RegionName { get; set; }

        [JsonProperty("costIndex")]
        public long CostIndex { get; set; }
    }
}
